version: "3.8"

services:
  backend:
    image: validator-monitor:latest
    build:
      context: ./validator-monitor/
      dockerfile: Dockerfile
    volumes:
      - ./monitor-logs:/usr/app/monitor-logs
      - ./grafana-dashboards/flare:/usr/app/grafana-dashboards
      - ./grafana-dashboard-templates:/usr/app/grafana-dashboard-templates
    ports:
      - "8502:8502"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana-oss
    volumes:
      - ./grafana-storage:/var/lib/grafana
      - ./grafana-custom.ini:/etc/grafana/grafana.ini
      - ./grafana-provisioning:/etc/grafana/provisioning
      - ./grafana-dashboards:/etc/dashboards
    ports:
      - "3000:3000"
